#!/usr/bin/env bash
set -e

REPO="https://raw.githubusercontent.com/rnutt13/claude-web-design/main"
PROJECT_DIR="$HOME/Claude Web Design"

echo ""
echo "Installing Claude Web Design — Disney team"
echo "==========================================="

mkdir -p "$PROJECT_DIR/.claude/commands"
mkdir -p "$PROJECT_DIR/assets/logos/disney"
mkdir -p "$PROJECT_DIR/assets/logos/salesforce"
mkdir -p "$PROJECT_DIR/assets/logos/common"
mkdir -p "$PROJECT_DIR/projects/disney"
mkdir -p "$PROJECT_DIR/projects/salesforce"

echo "Pulling config files..."
curl -fsSL "$REPO/config/CLAUDE.md" -o "$PROJECT_DIR/CLAUDE.md"
curl -fsSL "$REPO/config/commands/salesforce-brand.md" -o "$PROJECT_DIR/.claude/commands/salesforce-brand.md"
curl -fsSL "$REPO/config/commands/disney-brand.md" -o "$PROJECT_DIR/.claude/commands/disney-brand.md"
curl -fsSL "$REPO/config/commands/disneyplus-brand.md" -o "$PROJECT_DIR/.claude/commands/disneyplus-brand.md"

echo "Downloading Disney logos..."
D="$PROJECT_DIR/assets/logos/disney"
curl -fsSL "$REPO/assets/disney/imgi_34_The-Walt-Disney-Studios1.png" -o "$D/imgi_34_The-Walt-Disney-Studios1.png"
curl -fsSL "$REPO/assets/disney/imgi_35_Walt-Disney-Animation-Studios-Logo.jpg" -o "$D/imgi_35_Walt-Disney-Animation-Studios-Logo.jpg"
curl -fsSL "$REPO/assets/disney/imgi_36_Pixar-Logo.jpg" -o "$D/imgi_36_Pixar-Logo.jpg"
curl -fsSL "$REPO/assets/disney/imgi_37_MARVEL_STUDIOS_LOGO.jpg" -o "$D/imgi_37_MARVEL_STUDIOS_LOGO.jpg"
curl -fsSL "$REPO/assets/disney/imgi_38_1920-lucasfilm-logo.jpg" -o "$D/imgi_38_1920-lucasfilm-logo.jpg"
curl -fsSL "$REPO/assets/disney/imgi_39_Disney-Theatrical-Group1.png" -o "$D/imgi_39_Disney-Theatrical-Group1.png"
curl -fsSL "$REPO/assets/disney/imgi_40_20th_century_studios.png" -o "$D/imgi_40_20th_century_studios.png"
curl -fsSL "$REPO/assets/disney/imgi_41_SLP-logo.png" -o "$D/imgi_41_SLP-logo.png"
curl -fsSL "$REPO/assets/disney/imgi_42_200723_20th_01.jpg" -o "$D/imgi_42_200723_20th_01.jpg"
curl -fsSL "$REPO/assets/disney/imgi_43_ABCEnt_2018LogoForRelease.png" -o "$D/imgi_43_ABCEnt_2018LogoForRelease.png"
curl -fsSL "$REPO/assets/disney/imgi_44_2018-abc-news-logo-promo-black.png" -o "$D/imgi_44_2018-abc-news-logo-promo-black.png"
curl -fsSL "$REPO/assets/disney/imgi_45_ABC_signature_png.png" -o "$D/imgi_45_ABC_signature_png.png"
curl -fsSL "$REPO/assets/disney/imgi_46_ABC_OTV-HORIZONTAL-STACKED_BW-FLAT_2022.png" -o "$D/imgi_46_ABC_OTV-HORIZONTAL-STACKED_BW-FLAT_2022.png"
curl -fsSL "$REPO/assets/disney/imgi_47_Disney-Branded-Television_horizontal.png" -o "$D/imgi_47_Disney-Branded-Television_horizontal.png"
curl -fsSL "$REPO/assets/disney/imgi_48_Freeform_Wordmark_RGB_Electric-Pink91.png" -o "$D/imgi_48_Freeform_Wordmark_RGB_Electric-Pink91.png"
curl -fsSL "$REPO/assets/disney/imgi_49_FX-Logo-.png" -o "$D/imgi_49_FX-Logo-.png"
curl -fsSL "$REPO/assets/disney/imgi_50_HuluOriginals_800px.png" -o "$D/imgi_50_HuluOriginals_800px.png"
curl -fsSL "$REPO/assets/disney/imgi_51_NG_logo_black.png" -o "$D/imgi_51_NG_logo_black.png"
curl -fsSL "$REPO/assets/disney/imgi_52_D_Blue-Logo.png" -o "$D/imgi_52_D_Blue-Logo.png"
curl -fsSL "$REPO/assets/disney/imgi_53_hulu-logo.png" -o "$D/imgi_53_hulu-logo.png"
curl -fsSL "$REPO/assets/disney/imgi_54_Hotstar-reverse-logo.jpg" -o "$D/imgi_54_Hotstar-reverse-logo.jpg"
curl -fsSL "$REPO/assets/disney/imgi_55_Disney-Music-Group1.png" -o "$D/imgi_55_Disney-Music-Group1.png"
curl -fsSL "$REPO/assets/disney/imgi_56_ESPN-Logo.jpg" -o "$D/imgi_56_ESPN-Logo.jpg"
curl -fsSL "$REPO/assets/disney/imgi_57_ESPN_PLUS_LOGO-1.png" -o "$D/imgi_57_ESPN_PLUS_LOGO-1.png"
curl -fsSL "$REPO/assets/disney/imgi_58_Disneyland-Logo.jpg" -o "$D/imgi_58_Disneyland-Logo.jpg"
curl -fsSL "$REPO/assets/disney/imgi_59_Walt-Disney-World.png" -o "$D/imgi_59_Walt-Disney-World.png"
curl -fsSL "$REPO/assets/disney/imgi_60_Shanghai-Disney-Resort-Logo1.jpg" -o "$D/imgi_60_Shanghai-Disney-Resort-Logo1.jpg"
curl -fsSL "$REPO/assets/disney/imgi_61_Disneyland-Paris-Logo-Jan-2026.png" -o "$D/imgi_61_Disneyland-Paris-Logo-Jan-2026.png"
curl -fsSL "$REPO/assets/disney/imgi_62_Tokyo-Disney-Resort-Logo.jpg" -o "$D/imgi_62_Tokyo-Disney-Resort-Logo.jpg"
curl -fsSL "$REPO/assets/disney/imgi_63_Hong-Kong-Disneyland-Logo.jpg" -o "$D/imgi_63_Hong-Kong-Disneyland-Logo.jpg"
curl -fsSL "$REPO/assets/disney/imgi_64_DCL_logo_vert_BLUE_Crop.png" -o "$D/imgi_64_DCL_logo_vert_BLUE_Crop.png"
curl -fsSL "$REPO/assets/disney/imgi_65_Disney-Vacation-Club.png" -o "$D/imgi_65_Disney-Vacation-Club.png"
curl -fsSL "$REPO/assets/disney/imgi_66_Aulani-Logo.jpg" -o "$D/imgi_66_Aulani-Logo.jpg"
curl -fsSL "$REPO/assets/disney/imgi_67_AdventuresbyDisney.png" -o "$D/imgi_67_AdventuresbyDisney.png"
curl -fsSL "$REPO/assets/disney/imgi_68_WDI_Logo.png" -o "$D/imgi_68_WDI_Logo.png"
curl -fsSL "$REPO/assets/disney/imgi_69_Disney-Publishing-Worldwide-041.png" -o "$D/imgi_69_Disney-Publishing-Worldwide-041.png"
curl -fsSL "$REPO/assets/disney/imgi_70_CPC-Disney-store_shopDisney_Logo-Blue_2019_10_15.jpg" -o "$D/imgi_70_CPC-Disney-store_shopDisney_Logo-Blue_2019_10_15.jpg"
curl -fsSL "$REPO/assets/disney/imgi_71_ot_company_logo.png" -o "$D/imgi_71_ot_company_logo.png"
curl -fsSL "$REPO/assets/disney/MickeyMouse.png" -o "$D/MickeyMouse.png"
curl -fsSL "$REPO/assets/disney/The%20Walt%20Disney%20Company.svg" -o "$D/The Walt Disney Company.svg"

echo "Downloading Salesforce and common logos..."
curl -fsSL "$REPO/assets/salesforce/Salesforce.png" -o "$PROJECT_DIR/assets/logos/salesforce/Salesforce.png"
curl -fsSL "$REPO/assets/aws.png" -o "$PROJECT_DIR/assets/logos/common/aws.png"
curl -fsSL "$REPO/assets/Slack.png" -o "$PROJECT_DIR/assets/logos/common/Slack.png"
curl -fsSL "$REPO/assets/mulesoft.png" -o "$PROJECT_DIR/assets/logos/common/mulesoft.png"
curl -fsSL "$REPO/assets/claude.svg" -o "$PROJECT_DIR/assets/logos/common/claude.svg"
curl -fsSL "$REPO/assets/cursor.webp" -o "$PROJECT_DIR/assets/logos/common/cursor.webp"
curl -fsSL "$REPO/assets/ChatGPT.png" -o "$PROJECT_DIR/assets/logos/common/ChatGPT.png"
curl -fsSL "$REPO/assets/GCP%20small.avif" -o "$PROJECT_DIR/assets/logos/common/GCP small.avif"

echo "disney" > "$PROJECT_DIR/.team"
curl -fsSL "$REPO/VERSION" -o "$PROJECT_DIR/.version"

echo "Installing claude-wd CLI..."
if [ -w "/usr/local/bin" ]; then
  curl -fsSL "$REPO/bin/claude-wd" -o "/usr/local/bin/claude-wd"
  chmod +x "/usr/local/bin/claude-wd"
else
  sudo curl -fsSL "$REPO/bin/claude-wd" -o "/usr/local/bin/claude-wd"
  sudo chmod +x "/usr/local/bin/claude-wd"
fi

echo ""
echo "Done. Installed to: $PROJECT_DIR"
echo ""
echo "Next steps:"
echo "  1. Open \"$PROJECT_DIR\" in Claude Code."
echo "  2. Run /disney-brand, /disneyplus-brand, or /salesforce-brand to load brand tokens."
echo "  3. New HTML files will be saved to $PROJECT_DIR/projects/"
echo ""
echo "To update later:  claude-wd --update"
echo "To check version: claude-wd --version"
echo ""
